apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs-task3
  labels: 
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task3
  template:
    metadata:
      name: jenkins-rs
      labels:
        app: task3
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:jdk11
          ports:
            - containerPort: 8080
