apiVersion: v1
kind: Pod
metadata:
  name: kuar-task2
  labels:
    app: kuar
spec:
  containers:
    - name: kuar
      image: gcr.io/kuar-demo/kuard-amd64:1
      ports:
        - containerPort: 8080
