apiVersion: v1
kind: Pod
metadata:
  name: redis-task2
  namespace: test
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: redis-task2
    namespace: dev
    labels:
      app: redis
  spec:
    containers:
      - name: redis
        image: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
- apiVersion: v1
  kind: Pod
  metadata:
    name: redis-task2
    namespace: prod
    labels:
      app: redis
  spec:
    containers:
      - name: redis
        image: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
